import tweepy
import numpy as np
import pandas as pd
import time
import os
import csv
import json
import concurrent.futures


def chunker(sequence, num_of_chunks):
    return (sequence[position:position + num_of_chunks]
            for position in range(0, len(sequence), num_of_chunks))


def get_history(uid_key):
    try:
        # extracting the required information
        user_id = uid_key[0]
        keys = uid_key[1]
        #i = uid_key[2]
        # db = uid_key[2]

        # print(user_id)
        # print(keys)
        # print(db)

        access_token = keys['access']
        access_token_secret = keys['accessSecret']
        consumer_key = keys['consumer']
        consumer_secret = keys['consumerSecret']
        try:
            auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
            auth.set_access_token(access_token, access_token_secret)
            api = tweepy.API(auth_handler=auth, wait_on_rate_limit=True,
                             wait_on_rate_limit_notify=True,
                             retry_errors=[401, 403, 404, 418, 500, 503],
                             retry_count=5, retry_delay=5)

            CSVFile = '.csv'
            TxtFile = '.txt'
            JsonFile = '.json'
            user_timeline = []
            ScreenName = user_id

            # creating the files to save the information
            filenameCSV = ScreenName + CSVFile
            filenameTxt = ScreenName + TxtFile
            filenameJson = ScreenName + JsonFile

            # common folder path
            
            CSVFolder = 'csv'
            TxtFolder = 'txt'
            JsonFolder = 'json'

            # create location of the folder
            CommonFolder = './MacroUserTweets_'
            FolderPathCSV = CommonFolder + '/' + 'Tweets' + '/' + CSVFolder
            FolderPathTxt = CommonFolder + '/' + 'Tweets' + '/' + TxtFolder
            FolderPathJson = CommonFolder + '/' + 'Tweets' + '/' + JsonFolder

            # checking the folder path
            try:
                if os.path.isdir(FolderPathCSV) and os.path.isdir(FolderPathTxt) and os.path.isdir(FolderPathJson):
                    #print('Folders Exists')
                    pass
                else:
                    #print('Make new directories')
                    os.makedirs(FolderPathCSV)
                    os.makedirs(FolderPathTxt)
                    os.makedirs(FolderPathJson)
            except IOError as err:
                print(err)

            # open txt file
            CompletePathTxt = os.path.join(FolderPathTxt, filenameTxt)
            SaveFileTxt = open(CompletePathTxt, 'w', encoding='utf-8')

            # open csv file
            CompletePathCSV = os.path.join(FolderPathCSV, filenameCSV)
            SaveFileCSV = open(CompletePathCSV, 'w', encoding='utf-8')
            writer = csv.writer(SaveFileCSV, quoting=csv.QUOTE_MINIMAL)
            writer.writerow(
                ['ScreenName', 'created_at', 'tweet_id', 'text', 'RetweetOrNot', 'retweet_count', 'favorite_count',
                 'lang', 'hashtags', 'user_mentions'])

            # open json file
            CompletePathJson = os.path.join(FolderPathJson, filenameJson)
            SaveFileJson = open(CompletePathJson, 'w', encoding='utf8')

            # saving the summary of the history crawl
            filenameCSV_summary = 'CrawlHistorySummary' + CSVFile
            FolderPathCSV_summary = CommonFolder
            CompletePathCSV_summary = os.path.join(FolderPathCSV_summary, filenameCSV_summary)
            SaveFileCSV_summary = open(CompletePathCSV_summary, 'a', encoding='utf-8')
            writer_summary = csv.writer(SaveFileCSV_summary, quoting=csv.QUOTE_MINIMAL)
            writer_summary.writerow(['ScreenName', 'CollectedTweets'])

            counter = 0
            # tweet_text_all = []
            # number of tweets to collect
            num_of_tweet = 200
            try:
                user_timeline = api.user_timeline(screen_name=user_id, count=num_of_tweet,
                                                            tweet_mode='extended')
            except tweepy.TweepError as error:
                print('Error Generated by Tweepy API')
                print(error.reason)
                pass

            except Exception as e:
                print("Exception not from the API")
                print(e)
                pass

            if user_timeline is not None:
                for tweet in user_timeline:
                    # print(tweet)
                    # print(tweet.user.screen_name)
                    screen_name = tweet.user.screen_name
                    # print(tweet.created_at)
                    created_at = tweet.created_at
                    # print(tweet.id_str)
                    id_str = str(tweet.id_str)

                    # print(tweet.full_text)
                    # print(tweet.retweeted_status.full_text if tweet.full_text.startswith("RT @") else tweet.full_text)
                    # full_text = tweet.retweeted_status.full_text if tweet.full_text.startswith("RT @") else tweet.full_text

                    # this approach is not giving any errors
                    full_text = tweet.full_text[3:] if tweet.full_text.startswith("RT @") else tweet.full_text
                    # print(full_text)
                    
                    # tweet_text_all.append(full_text)

                    # print(1 if tweet.full_text.startswith("RT @") else 0)
                    CheckRetweet = str(1 if tweet.full_text.startswith("RT @") else 0)

                    # print(tweet.retweet_count)
                    retweet_count = tweet.retweet_count
                    # print(tweet.favorite_count)
                    favorite_count = tweet.favorite_count
                    lang = tweet.lang

                    # hashtags
                    # print(tweet.entities['hashtags'])
                    hashtags = [hashtag["text"] for hashtag in tweet.entities["hashtags"]]
                    hashtags = ";".join(hashtags) if hashtags else ""
                    # print(hashtags)

                    # user-mentions-name
                    # print(tweet.entities['user_mentions'])
                    user_mentions_name = [x["screen_name"] for x in tweet.entities["user_mentions"]]
                    user_mentions_name = ";".join(user_mentions_name) if user_mentions_name else ""
                    # print(user_mentions_name)
                    # print('\n')
                    # saving files in different formats
                    SaveFileTxt.write(full_text + '\n')
                    writer.writerow(
                        [screen_name, created_at, id_str, full_text, CheckRetweet, retweet_count, favorite_count, lang,
                         hashtags, user_mentions_name])
                    json.dump(tweet._json, SaveFileJson, indent=4, sort_keys=True)
                    counter += 1

            SaveFileTxt.close()
            SaveFileJson.close()
            SaveFileCSV.close()
            writer_summary.writerow([ScreenName, counter])
            #print('Total Tweets/Retweets {0} for User {1}'.format(counter, ScreenName))
            SaveFileCSV_summary.close()
            
            print('Total {0} for User {1}'.format(counter, ScreenName))
            
            #return tweet_text_all
        except Exception as e:
            print("Error Authentication")
            print(e)

    except Exception as e:
        print(e)


if __name__ == "__main__":
    CommonFilePath = "./ExtractedSamplesV3"
    Filename = "TopFollowerLabelsUpdated.csv"
    CompleteCompletePath = os.path.join(CommonFilePath, Filename)
    TopFollowerDF = pd.read_csv(CompleteCompletePath, encoding="utf-8", low_memory=False)
    celebrities_username = list(TopFollowerDF["users"])

    # save the information of the tweets

    # getting the keys
    try:
        with open('api_keys_currently_working.json') as json_file:
            api_keys = json.load(json_file)
    except FileNotFoundError:
        print("Key file not found or wrong path")

    # extracting the information from the json file
    key_names = [key for key in api_keys]
    # print(key_names)
    userNum = 0
    chunk_size = 60
    loopStopper = True
    while loopStopper:
        for group in chunker(sequence=celebrities_username, num_of_chunks=chunk_size):
            user_names_subset = list(i for i in group)
            key_subset = key_names[0:chunk_size]
            # crawling for users
            print('Users that will be crawled')
            print(user_names_subset)
            print('Total Users : {0}'.format(len(user_names_subset)))
            user_with_key = []
            for index in range(len(user_names_subset)):
                temp = (user_names_subset[index], api_keys[key_subset[index]])  # , db
                user_with_key.append(temp)
            # print(user_with_key)
            # carrying out the threading
            print("Start Execute Threading")
            try:
                with concurrent.futures.ThreadPoolExecutor(max_workers=len(user_names_subset)) as executor:
                    executor.map(get_history, user_with_key)
            except Exception as err:
                print("Unable to perform threading")
                print(err)
            userNum = userNum + len(group)
            print('# of Users Completed: {0}'.format(userNum))

        loopStopper = False
    print('\n')
    print('EOF')
#BUSC Trip 2023 Refund MD SADDAM HOSSAIN from BHUIYA SAAD
