"""
This script is used for Random Sampling Weighted
"""

import os
import pandas as pd
import AllTwitterKeys
import tweepy
import csv


class TwitterAuthentication:

    # constructor
    def __init__(self):
        pass

    @staticmethod
    def twitter_authenticate():
        auth = tweepy.OAuthHandler(AllTwitterKeys.key_105['consumer'], AllTwitterKeys.key_105['consumerSecret'])
        auth.set_access_token(AllTwitterKeys.key_105['access'], AllTwitterKeys.key_105['accessSecret'])
        return auth


class TwitterDataExtraction:

    # constructor
    def __init__(self):
        self.twitter_authenticator = TwitterAuthentication()
        auth = self.twitter_authenticator.twitter_authenticate()
        self.api = tweepy.API(auth_handler=auth, wait_on_rate_limit=True,
                              wait_on_rate_limit_notify=True,
                              retry_errors=[401, 403, 404, 418, 500, 503],  # https://www.myintervals.com/api/errors.php
                              retry_count=5, retry_delay=5)

    def get_profile_info(self, name):

        # initialize variables
        name_twitter = None
        id_str = None
        screen_name = None
        location = None
        description = None
        verified = None
        protected = None
        followers_count = None
        friends_count = None
        statuses_count = None

        try:
            user_info = self.api.get_user(name)

            name_twitter = user_info.name
            id_str = user_info.id_str
            screen_name = user_info.screen_name
            location = user_info.location
            description = user_info.description
            verified = user_info.verified
            protected = user_info.protected
            followers_count = user_info.followers_count
            friends_count = user_info.friends_count
            statuses_count = user_info.statuses_count

        except tweepy.TweepError as error:
            print('Error Generated by Tweepy')
            #print(error.reason)
            if error.api_code == 50 or error.api_code == 63:
                print('User either suspended or not found: {0}'.format(name))

        completeData = [name, id_str, name_twitter, location, description, verified, protected, followers_count,
                        friends_count, statuses_count]

        return completeData


if __name__ == '__main__':

    CommonFolderPath = './ExtractedSamplesV2_New/'

    Sample_1_FolderPath = CommonFolderPath + 'Sample_1'
    Sample_2_FolderPath = CommonFolderPath + 'Sample_2'
    Sample_3_FolderPath = CommonFolderPath + 'Sample_3'
    Sample_4_FolderPath = CommonFolderPath + 'Sample_4'
    Sample_5_FolderPath = CommonFolderPath + 'Sample_5'
    try:
        CheckFolderPath_sample1 = os.path.isdir(Sample_1_FolderPath)
        CheckFolderPath_sample2 = os.path.isdir(Sample_2_FolderPath)
        CheckFolderPath_sample3 = os.path.isdir(Sample_3_FolderPath)
        CheckFolderPath_sample4 = os.path.isdir(Sample_4_FolderPath)
        CheckFolderPath_sample5 = os.path.isdir(Sample_5_FolderPath)
        if CheckFolderPath_sample1 and CheckFolderPath_sample2 and CheckFolderPath_sample3 and CheckFolderPath_sample4 and CheckFolderPath_sample5:
            pass
        else:
            os.makedirs(Sample_1_FolderPath)
            os.makedirs(Sample_2_FolderPath)
            os.makedirs(Sample_3_FolderPath)
            os.makedirs(Sample_4_FolderPath)
            os.makedirs(Sample_5_FolderPath)

    except BaseException as err:
        print('Error Creating the Directory')
        print(err)

    FileName = 'MostFollowedTwitterUsers.csv'
    FolderPath = './MostFollowedTwitterProfile'
    CompletePath = os.path.join(FolderPath, FileName)
    UserFollower_df = pd.read_csv(CompletePath, encoding='utf-8')
    """
    # get the random sample w/o replacement
    Contain_sample_1 = UserFollower_df.iloc[1000:5000, :]
    Contain_sample_2 = UserFollower_df.iloc[5000:10000, :]
    Contain_sample_3 = UserFollower_df.iloc[10000:15000, :]
    """

    # new set of random samples
    Contain_sample_1 = UserFollower_df.iloc[1000:4000, :]
    Contain_sample_2 = UserFollower_df.iloc[4000:7000, :]
    Contain_sample_3 = UserFollower_df.iloc[7000:10000, :]
    Contain_sample_4 = UserFollower_df.iloc[10000:12000, :]
    Contain_sample_5 = UserFollower_df.iloc[12000:15000, :]


    """
    #print('Actual Size: {0}'.format(UserFollower_df.shape)) #(16349, 6)
    #print('Sample-1 Size : {0}'.format(Contain_sample_1.shape)) #(4000, 6)
    #print('Sample-2 Size : {0}'.format(Contain_sample_2.shape)) #(5000, 6)
    #print('Sample-3 Size : {0}'.format(Contain_sample_3.shape)) #(5000, 6)
    """

    sample_1_username = Contain_sample_1['ScreenName'].sample(n=110, random_state=1, axis=0, replace=False)
    sample_2_username = Contain_sample_2['ScreenName'].sample(n=110, random_state=1, axis=0, replace=False)
    sample_3_username = Contain_sample_3['ScreenName'].sample(n=110, random_state=1, axis=0, replace=False)
    sample_4_username = Contain_sample_4['ScreenName'].sample(n=110, random_state=1, axis=0, replace=False)
    sample_5_username = Contain_sample_5['ScreenName'].sample(n=110, random_state=1, axis=0, replace=False)

    # extract the profile of the see if they are all active
    client = TwitterDataExtraction()
    for i in range(1, 6):
        Sample_filename = 'Profile_Sample_' + str(i) + '.csv'
        Sample_CompletePath = os.path.join(globals()['Sample_%s_FolderPath' % i], Sample_filename)
        Sample_csv_file = open(Sample_CompletePath, 'w')
        Sample_writer = csv.writer(Sample_csv_file, quoting=csv.QUOTE_MINIMAL)
        Sample_writer.writerow(['screen_name', 'id', 'name', 'location', 'description',
                                'verified', 'protected', 'followers_count', 'friends_count', 'statuses_count'])

        print('Extracting Sample-{0}'.format(i))
        for user in globals()['sample_%s_username' % i]:
            print('User: {0}'.format(user))
            ProfileInfo = client.get_profile_info(name=user)
            Sample_writer.writerow([ProfileInfo[0], ProfileInfo[1], ProfileInfo[2], ProfileInfo[3], ProfileInfo[4],
                                    ProfileInfo[5], ProfileInfo[6], ProfileInfo[7], ProfileInfo[8], ProfileInfo[9]])

        Sample_csv_file.close()
        print('Done Extraction Sample-{0}'.format(i))

    # saving the names of the active samples
    for index in range(1, 6):
        file = 'Profile_Sample_' + str(index) + '.csv'
        SampleFilePath = CommonFolderPath + 'Sample_' + str(index)
        CompleteSamplePath = os.path.join(SampleFilePath, file)
        sample_df = pd.read_csv(CompleteSamplePath, encoding='utf-8')

        print('Sample: {0} Loaded'.format(index))
        # open txt file to save the information
        TxtFile = 'Sample_' + str(index) + '_Users.txt'
        CompleteSamplePath_txt = os.path.join(SampleFilePath, TxtFile)
        SaveTxtFile = open(CompleteSamplePath_txt, 'w', encoding='utf-8')

        # get the active users
        selected_rows = sample_df.loc[(sample_df['protected'].isin([False]))] # sample_df['verified'].isin([True]) &
        totalUsers = selected_rows['screen_name']
        selectedUsers = totalUsers[:100]
        print('# of Users Selected: {0}'.format(len(selectedUsers)))

        # write in a text file
        for user in selectedUsers:
            SaveTxtFile.write(user + '\n')
        SaveTxtFile.close()
        print('Users of Sample: {0} Saved'.format(index))

    print('EOF')
